name: Add issues to project columns based on issue events

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Add new issues to project column 'ToDo'
        uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'opened'
        with:
          project-url: https://github.com/orgs/GraphicEditStudio/projects/10/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          column-name: ToDo

      - name: Move assigned issues to 'In progress' column in project
        uses: actions/add-to-project@v0.5.0
        if: github.event.action == 'assigned'
        with:
          project-url: https://github.com/orgs/GraphicEditStudio/projects/10/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          column-name: In progress

